export const ITEMS_PER_PAGE = 50;

export const COLORS = [
    "Red",
    "Blue",
    "Green",
    "Yellow",
    "Purple",
    "Orange",
    "Pink",
    "Brown",
    "Black",
    "White",
    "Gray",
    "Cyan",
    "Magenta",
    "Lime",
    "Teal",
    "Navy",
    "Silver",
    "Gold",
    "Indigo",
    "Maroon",
    "Turquoise",
    "Violet",
    "Coral",
    "Salmon",
    "Olive",
    "Slate",
    "Plum",
    "Lavender",
    "Mint",
    "Beige",
    "Periwinkle",
    "Khaki",
    "Crimson",
    "Moccasin",
    "Aquamarine",
    "Chartreuse",
    "Cornsilk",
    "Darkorchid",
    "Firebrick",
    "Honeydew",
    "Ivory",
    "Linen",
    "Midnightblue",
    "Navajowhite",
    "Papayawhip",
    "Rosybrown",
    "Seashell",
    "Snow",
    "Thistle",
    "Tomato",
    "Wheat",
  ];
  
  